### ISSUE TITLE
Error Adding an exam.

### ISSUE THREAD

**Issue by rafati** [UniTime/unitime#6] opened 2015-09-25 14:49 UTC
Hi, 
I keep getting the error below when clicking the save button while editing or adding an exam in the course offering page. I got the error in a vanilla installation of version 4.1.77, 4.0.35 and 4.0.17.

Best Regards.
Rafat

[09/25/15 17:42:47] ERROR  ClassCastException -> java.lang.String cannot be cast to java.lang.Long
java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Long
	at org.unitime.timetable.form.ExamEditForm.getSubjectArea(ExamEditForm.java:166)
	at org.unitime.timetable.form.ExamEditForm.getExamOwner(ExamEditForm.java:320)
	at org.unitime.timetable.form.ExamEditForm.validate(ExamEditForm.java:428)
	at org.unitime.timetable.action.ExamEditAction.execute(ExamEditAction.java:239)
	at org.springframework.web.struts.DelegatingActionProxy.execute(DelegatingActionProxy.java:113)
	at org.apache.struts.action.RequestProcessor.processActionPerform(RequestProcessor.java:425)
	at org.apache.struts.action.RequestProcessor.process(RequestProcessor.java:228)
	at org.apache.struts.action.ActionServlet.process(ActionServlet.java:1913)
	at org.apache.struts.action.ActionServlet.doPost(ActionServlet.java:462)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:650)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.unitime.timetable.filter.LocaleFilter.doFilter(LocaleFilter.java:87)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.unitime.timetable.filter.NoCacheFilter.doFilter(NoCacheFilter.java:60)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.unitime.timetable.filter.QueryLogFilter.doFilter(QueryLogFilter.java:110)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.unitime.timetable.filter.PageAccessFilter.doFilter(PageAccessFilter.java:161)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.unitime.timetable.filter.MessageLogFilter.doFilter(MessageLogFilter.java:93)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330)
	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:118)
	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:84)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
	at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:113)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
	at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:103)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
	at org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:113)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
	at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:154)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
	at org.springframework.security.web.savedrequest.RequestCacheAwareFilter.doFilter(RequestCacheAwareFilter.java:45)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
	at org.springframework.security.web.authentication.www.BasicAuthenticationFilter.doFilter(BasicAuthenticationFilter.java:150)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
	at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:199)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
	at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:110)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
	at org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:50)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:106)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
	at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:87)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
	at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:192)
	at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:160)
	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:343)
	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:260)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.unitime.timetable.filter.HibSessionFilter.doFilter(HibSessionFilter.java:70)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.unitime.timetable.filter.EncodingFilter.doFilter(EncodingFilter.java:50)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:505)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:170)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:956)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:423)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1079)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:625)
	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:318)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)
[09/25/15 17:42:47] WARN   RequestProcessor -> Unhandled Exception thrown: class java.lang.ClassCastException
[09/25/15 17:42:47] WARN   PageAccessFilter -> javax.servlet.ServletException: java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Long seen on page /UniTime/examEdit.do (page took 0.01 s).
  User: admin (SYSADMIN_FAL2015BU [Session:Fal2015BU, TimetableManager:1, Role:Sysadmin])
  Request parameters:
    examId=
    nextId=
    previousId=
    clone=false
    op2=
    op=Save
    name=
    examType=1540049
    length=120
    seatingType=Exam
    maxNbrRooms=4
    size=
    printOffset=
    note=
    instructors[0]=-
    instructors[1]=-
    subjectArea[0]=2064544
    courseNbr[0]=3244034
    itype[0]=-9223372036854775807
    classNumber[0]=-1
    subjectArea[1]=-1
    courseNbr[1]=-1
    itype[1]=0
    classNumber[1]=-1
    subjectArea[2]=-1
    courseNbr[2]=-1
    itype[2]=0
    classNumber[2]=-1
    PeriodPref_reqSelect=0
    PeriodPref_nrTimes=3
    PeriodPref_nrDays=7
    PeriodPref_nrSelections=1
    PeriodPref_req_0_0=0
    PeriodPref_req_1_0=0
    PeriodPref_req_2_0=0
    PeriodPref_req_3_0=0
    PeriodPref_req_4_0=0
    PeriodPref_req_5_0=0
    PeriodPref_req_6_0=0
    PeriodPref_req_0_1=0
    PeriodPref_req_1_1=0
    PeriodPref_req_2_1=0
    PeriodPref_req_3_1=0
    PeriodPref_req_4_1=0
    PeriodPref_req_5_1=0
    PeriodPref_req_6_1=0
    PeriodPref_req_0_2=0
    PeriodPref_req_1_2=0
    PeriodPref_req_2_2=0
    PeriodPref_req_3_2=0
    PeriodPref_req_4_2=0
    PeriodPref_req_5_2=0
    PeriodPref_req_6_2=0
    PeriodPref_reqUsed=0
    roomGroups[0]=-
    roomGroupLevels[0]=-
    roomGroups[1]=-
    roomGroupLevels[1]=-
    roomGroups[2]=-
    roomGroupLevels[2]=-
    roomGroups[3]=-
    roomGroupLevels[3]=-
    roomPrefs[0]=-
    roomPrefLevels[0]=-
    roomPrefs[1]=-
    roomPrefLevels[1]=-
    roomPrefs[2]=-
    roomPrefLevels[2]=-
    roomPrefs[3]=-
    roomPrefLevels[3]=-
    bldgPrefs[0]=-
    bldgPrefLevels[0]=-
    bldgPrefs[1]=-
    bldgPrefLevels[1]=-
    bldgPrefs[2]=-
    bldgPrefLevels[2]=-
    bldgPrefs[3]=-
    bldgPrefLevels[3]=-
    roomFeaturePrefs[0]=-
    roomFeaturePrefLevels[0]=-
    roomFeaturePrefs[1]=-
    roomFeaturePrefLevels[1]=-
    roomFeaturePrefs[2]=-
    roomFeaturePrefLevels[2]=-
    roomFeaturePrefs[3]=-
    roomFeaturePrefLevels[3]=-
    deleteType=
    deleteId=
    reloadCause=

**Comment by rafati** [comment] 2015-09-25 14:54
By the way, I couldn't replicate this error at demo.unitime.org, but I was able to replicate it in two different machines (windows and mac) pointing to two different databases.

**Comment by tomas-muller** [comment] 2015-09-25 15:49
I am not able to reproduce this issue. The ExamEditForm.subjectArea contains a list of unique ids (Long type) and I do not see how a string can creep in.

Could you try to delete the content of Tomcat/work directory to make sure that the current version of the Add/Edit Examination JSP page is compiled/used.

Could you please provide us with more details about your setup? For instance, what version of Java and Tomcat are you using?

**Comment by rafati** [comment] 2015-09-25 19:07
I cleared Tomcat/work directory and restarted the service and still getting the same results.
Here is the  two configurations I have:
Mac configuration:
Tomcat:
Apache Tomcat/7.0.64	
JVM 1.8.0_60-b27		
Mac OS X 10.10.5
x86_64
Free memory: 236.62 MB Total memory: 542.00 MB Max memory: 910.50 MB

Mysql 5.6.26 MySQL Community Server (GPL) compiled for osx10.8   (x86_64)
java version "1.8.0_60"
Java(TM) SE Runtime Environment (build 1.8.0_60-b27)
Java HotSpot(TM) 64-Bit Server VM (build 25.60-b23, mixed mode)
UnitTime Version 4.1.77 built on Fri, 25 Sep 2015

Windows configuration:
Apache Tomcat/7.0.62	
JVM Version 1.8.0_45-b15	
Windows 8 version 6.2	
amd64
Physical memory: 2047.54 MB Available memory: 190.01 MB Total page file: 6655.54 MB Free page file: 3580.23 MB Memory load: 90
Process kernel time: 6.281 s Process user time: 58.375 s
Mysql 5.6.25-log MySQL Community Server (GPL) compiled for x86_64
java version "1.8.0_45"
Java(TM) SE Runtime Environment (build 1.8.0_45-b15)
Java HotSpot(TM) 64-Bit Server VM (build 25.45-b02, mixed mode)
UnitTime: Version 4.0.17 built on Sat, 16 May 2015

**Comment by rafati** [comment] 2015-09-25 19:13
Is there a specific log type that I can turn on\elevate that may show more information about this error?
Thanks

**Comment by tomas-muller** [comment] 2015-09-25 19:52
Your setup (Mac) looks very similar to what I use for development. I am still unable to reproduce the problem.

Could you send me mysqldump of your database and an exact procedure that should reproduce the issue?

**Comment by tomas-muller** [comment] 2015-10-05 16:08
Fixed by commit edd7432.

**Closed by tomas-muller** 2015-10-05 16:08 UTC
