### ISSUE TITLE
Error in updating the class timetable

### ISSUE THREAD

**Issue by vaibhavi012** [UniTime/unitime#175] opened 2024-06-27 09:35 UTC
Hello @tomas-muller ,
The latest versions of unitime are not compatible with the rest of the tools. Error 404 not found page occurs after running the unitime. 
So I am working with 4.1_bld231 version. And I am facing the following error.

![ResultSet error](https://github.com/UniTime/unitime/assets/147844217/6469395c-c63b-4310-9c3b-5d8625dd028d)

**Comment by tomas-muller** [comment] 2024-06-27 10:02
Please provide the whole error message or, better yet, the Tomcat log. From the screenshot it is unclear why the SQLGrammarException is being thrown. I can only identify that the error was thrown during an update of the Edit Class page while clearing the existing class preferences.

If you were trying to update UniTime to a later version, it is possible that the database was already updated to a later version, and some of the changes made are not compatible with the 4.1 version. You can check the database version on the Administration > Utilities > Test HQL page, by submitting the following query:
```
select value from ApplicationConfig where key = 'tmtbl.db.version'
```

The latest build of UniTime 4.8 is on version 269. For UniTime 4.1.231, you should see version 160.
<img width="1035" alt="Screenshot 2024-06-27 at 11 56 33" src="https://github.com/UniTime/unitime/assets/10631634/999ee6d6-4fd4-4355-9f7b-e6bb36c4aa75">

Could you be more specific on what tools are not compatible? Please note that if you are using Java 8, you can only update to UniTime 4.7 as UniTime 4.8 requires Java 11. Tomcat needs to be 8.5 or 9.0, MySQL 8.x. UniTime 4.7 or earlier would work on MySQL 5.7 as well.

**Comment by vaibhavi012** [comment] 2024-06-27 10:29
![ResultSet error](https://github.com/UniTime/unitime/assets/147844217/718e212e-bf9b-4c8f-b420-853821a1498e)
![log](https://github.com/UniTime/unitime/assets/147844217/180c114a-ccda-438f-adb9-b7e76b457e25)
![error1](https://github.com/UniTime/unitime/assets/147844217/544b49ad-c3b0-459d-9fba-a10e2b58e0f5)
![error2](https://github.com/UniTime/unitime/assets/147844217/b1f96f6c-c70b-4adc-9b73-64d52ba1eb12)

**Comment by vaibhavi012** [comment] 2024-06-27 10:33
If I update to unitime 4.7 or 4.8 , i am getting 404 not found error in the browser when i try to run unitime of latest version. Even though i have tomcat 8.5 , MySQL 8 and MySQL Connector/J 8.4 . Could you please tell me what might be going wrong.

**Comment by tomas-muller** [comment] 2024-06-27 11:34
The problem is that you are using MySQL 8 with a UniTime version that is too old. MySQL 8 introduced a new [GROUPING function](https://dev.mysql.com/blog-archive/mysql-8-0-grouping-function/) that created an issue with a UniTime column named as such. This was fixed in comit 44b5b05 back in 2018 and is available in UniTime 4.3.112 or later. Alternatively, it should be possible to fix this by setting

```
hibernate.globally_quoted_identifiers=true
```

in the UniTime custom properties file. See issue #34 for more details.

Error 404 (page not found) indicates that either the URL is wrong (e.g., the UniTime.war was renamed before the deployment, which would result in a different URL) or that the deployment of UniTime (during the startup of the Tomcat) has failed. The Tomcat log from the deployment should provide more information about what has failed.

**Comment by vaibhavi012** [comment] 2024-07-01 09:43
I tried to install unitime version 4.5_bld177 with tomcat 8.5 version and MySQL 8 but i'm facing 404 error not found and logs are shown below: 
![image](https://github.com/UniTime/unitime/assets/147844217/17a854be-eba3-4e49-836a-40d8dab90ea1)

![image](https://github.com/UniTime/unitime/assets/147844217/ad35f8a0-89a1-49a4-b479-b029c280949a)

![image](https://github.com/UniTime/unitime/assets/147844217/200d7967-d299-4bd2-89a6-6bf6d7800ea3)

**Comment by tomas-muller** [comment] 2024-07-01 12:32
What version of Java are you using? As per the [UniTime 4.5 installation instructions](https://help45.unitime.org/installation):

> If you are using Java 16 or newer, you will need to set the --illegal-access=permit java option (e.g., using the JAVA_OPTS variable) as some of the UniTime dependencies do not support strong encapsulation yet.

Alternatively, you can use an older version of Java. Java 11 is a good choice as it offers LTS (long-time support). It can be an OpenJDK, such as [Eclipse Temurin](https://adoptium.net/temurin/releases/?version=11).

Full support for Java 16+ was added in UniTime 4.6.

I have recently updated the platform-specific installation instructions for UniTime 4.8, for instance, see [help48.unitime.org/manuals/installation-windows](https://help48.unitime.org/manuals/installation-windows) for Windows.

**Comment by vaibhavi012** [comment] 2024-07-09 07:04
Thank you @tomas-muller, I am able to setup the software with latest versions.
But I had a query relating to creating new academic session where after adding new session and switching to it, then there are missing features in the nav-bar as well as the newly created department is not showing up in subject area to create a new subject area.
Kindly help me with this.
![image](https://github.com/UniTime/unitime/assets/147844217/6c5d53ae-ad3d-4c81-a5b7-1337feda4eaf)
![image](https://github.com/UniTime/unitime/assets/147844217/89b093fc-b512-4ef6-ae57-df5bf9470695)

**Comment by tomas-muller** [comment] 2024-07-09 07:44
Some pages and the related menu items are only shown when relevant data is available. For instance, the Examinations menu is only available when any examination periods are defined for the current academic session (see Administration > Academic Sessions > Examination Periods). Similarly, for the Course Timetabling menu to show there must be at least one solver group defined (see Administration > Academic Sessions > Solver Groups).

As for the subject area, please assign the department to a timetabling manager first (see Administration > Academic Sessions > Timetabling Managers).

For more details, please take a look at our administrative manual (menu Help > Manuals > Administration, or [help.unitime.org/manuals/administration](https://help.unitime.org/manuals/administration). In particular, the First Academic Session section.

**Comment by vaibhavi012** [comment] 2024-07-16 09:09
With your response I was successfully able to explore the features, thank you @tomas-muller . 
I also wanted to know how to enroll new students in the new academic session. Kindly help me through this.

**Comment by tomas-muller** [comment] 2024-07-16 11:06
There are a few options:
1. You can import student class enrollments (using Student class enrollments XML (see [here](https://www.unitime.org/interface/studentEnrollmentImport.xml) for an example). The Administration > Academic Sessions > Data Exchange page can import the XML file.
2. You can import student course requests (using Student course requests XML (see [here](https://www.unitime.org/interface/woebegonStudents.xml) for an example) and then run the Student Scheduling Solver to enroll students in individual classes.
3. You can import just the students (using Students XML (see [here](https://www.unitime.org/interface/studentInfoImport.xml) for an example) and then let the students register themselves (using the [Student Course Requests](https://help.unitime.org/student-course-requests) page and then using the Student Scheduling Solver to enroll students in individual classes) or to enroll themselves into classes (using the [Student Scheduling Assistant](https://help.unitime.org/student-scheduling-assistant) page). For this, you need to have the academic session set in a status that allows for pre-registration and/or student scheduling: on Administration > Other > Status Types, the status needs to have the appropriate options checked in the Student Scheduling section.

For more details about the various XML imports, please see [https://www.unitime.org/uct_interfaces.php](https://www.unitime.org/uct_interfaces.php).

**Comment by vaibhavi012** [comment] 2024-07-18 11:02
Thank you @tomas-muller for guiding.

**Closed** 2024-07-18 14:14 UTC
